server:
  port: 8080

spring:
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-admin-console-changelog.xml
    default_schema: ${DB_SCHEMA:admin-console}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/skillbox
    username: ${DB_USERNAME:admin-console}
    password: ${DB_PASSWORD:admin-console}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${DB_SCHEMA:admin-console}
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 10MB
      resolve-lazily: true

cloudinary:
  config:
    cloud_name: da0wr9y51
    api_key: 439542312243829
    api_secret: FkPFGJDXGZAc3M5IqmIbFCQLXQw


