server:
  port: 8080

spring:
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-admin-console-changelog.xml

  datasource:
    url: jdbc:postgresql://postgres:5432/skillbox
    username: admin-console
    password: admin-console
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: admin-console
    open-in-view: false
