server:
  port: 8083
  tomcat:
    max-swallow-size: 100MB

spring:
  security:
    user:
      name: admin-console
      password: admin-console
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-admin-console-changelog.xml
    default_schema: admin-console

  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: admin-console
    password: admin-console
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: admin-console
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 10MB
      resolve-lazily: true

cloudinary:
  config:
    cloud_name: da0wr9y51
    api_key: 439542312243829
    api_secret: FkPFGJDXGZAc3M5IqmIbFCQLXQw

logging:
  level:
    org.springframework: info
